<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Library</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/all.min.css" rel="stylesheet">
    <link href="/css/styles.css" rel="stylesheet">
</head>
<body>
<?php \Snowdog\Academy\Component\Menu::getInstance()->render() ?>
<main>

<?php if (isset($_SESSION['flash'])): ?>
    <p class="bg-info"><?= $_SESSION['flash'] ?></p>
    <?php unset($_SESSION['flash']) ?>
<?php endif ?>