<?php require_once(__DIR__ . '/../common/header.phtml'); ?>

<div class="container">
    <div>
        <h1>Login Page</h1>
        <form class="form-horizontal" method="post" action="/login">
            <div class="form-group">
                <label for="input-login" class="col-sm-2 control-label">Login:</label>
                <div class="col-sm-10">
                    <input type="text" name="login" class="form-control" id="input-login" placeholder="Login">
                </div>
            </div>
            <div class="form-group">
                <label for="input-password" class="col-sm-2 control-label">Password:</label>
                <div class="col-sm-10">
                    <input type="password" name="password" class="form-control" id="input-password" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </div>
        </form>
    </div>
</div>

<?php require_once(__DIR__ . '/../common/footer.phtml'); ?>
