<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml');

$action = '/admin/new_book';
if ($this->book instanceof Book) {
    $title = $this->book->getTitle();
    $author = $this->book->getAuthor();
    $isbn = $this->book->getIsbn();
    $action = '/admin/edit_book/' . $this->book->getId();
}
?>

<section id="new-book-form" class="padded">
    <h3>Book Details Edit</h3>
    <form class="form-horizontal" method="POST" action="<?= $action ?>">
        <div class="form-group">
            <label for="book-title" class="col-sm-1 control-label">Title:</label>
            <div class="col-sm-10">
                <input type="text" id="book-title" name="title" class="form-control" value="<?= $title ?? ''?>" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="author" class="col-sm-1 control-label">Author:</label>
            <div class="col-sm-10">
                <input type="text" id="author" name="author" class="form-control" value="<?= $author ?? ''?>" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="isbn" class="col-sm-1 control-label">ISBN:</label>
            <div class="col-sm-10">
                <input type="text" id="isbn" name="isbn" class="form-control" value="<?= $isbn ?? ''?>" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2">
                <button type="submit" class="btn btn-primary">Save book</button>
            </div>
        </div>
    </form>
    <?php if ($isbn): ?>
        <form class="form-horizontal" method="POST" action="/admin/restore_by_isbn/<?= $this->book->getId() ?? ''?>">
            <div class="form-group">
                <div class="col-sm-offset-1 col-sm-2">
                    <button type="submit" class="btn btn-primary">Restore by ISBN</button>
                </div>
            </div>
        </form>
    <?php endif; ?>
</section>

<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>
