<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml');

?>

    <section id="new-book-form" class="padded">
        <h3>Import Books From CSV</h3>

        <form class="form-horizontal" method="POST" action="/admin/import_from_csv" enctype="multipart/form-data" >
            <div class="form-group">
                <label for="csv_file" class="col-sm-1 control-label">CSV File:</label>
                <div class="col-sm-10">
                    <input type="file" id="csv" name="csv_file" class="form-control" required/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-1 col-sm-2">
                    <button type="submit" class="btn btn-primary">Import Books</button>
                </div>
            </div>
        </form>
    </section>

<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>